### ISSUE TITLE
Consider cores reserved by the system (with focus on Slurm)

### ISSUE THREAD

**Issue by mtitov** [ExaWorks/psij-python#337]
Slurm provides feature core specialization: https://slurm.schedmd.com/core_spec.html
Crusher@OLCF started to reserve 8 cores per node by default ([link](https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html#id4))

> Slurm’s core specialization default will change: Slurm `--core-spec` or `-S` value will be set to 8. This will provide a symmetric distribution of cores per GCD to the application and will reserve one core per L3 cache region.

Core specialization could be disabled with `-S 0`

**Comment by hategan** [comment]
The general philosophy is that we abstract things that are common across schedulers and we provide "pass-through" for those that aren't. So if this is something found in other schedulers, we should probably add it to the API. Otherwise, use `spec.attributes.custom_attributes = {'slurm.core-spec': '0'}`. And it looks like this isn't documented...

**Comment by mtitov** [comment]
> Otherwise, use `spec.attributes.custom_attributes = {'slurm.core-spec': '0'}`

this looks good, thank you! Thus, this approach would always work, and in case of extending API, it will be just another way to describe this behavior

**Comment by hategan** [comment]
> this approach would always work

Yes, but only for SLURM. So use with caution.
