### ISSUE TITLE
Documentation: Update `ResourceSpec` to `ResourceSpecV1` in docs

### ISSUE THREAD

**Issue by arosen93** [ExaWorks/psij-python#396]
# Summary

When trying to pass in arguments to the `ResourceSpec`, I get an error state that it takes no arguments.

# Reproduction

Take the following example from the docs, for instance:

```python
from psij import JobSpec, ResourceSpec

spec = JobSpec()
spec.executable = '/bin/stress'
spec.resource_spec = ResourceSpec(node_count=2, processes_per_node=2,
        process_count=2)
# the line above should raise an 'psij.InvalidJobException' exception
```

As noted in the comment, it _should_ raise an `InvalidJobException`, but instead it raises a `TypeError`.

```python
TypeError                                 Traceback (most recent call last)
Cell In[1], line 5
      3 spec = JobSpec()
      4 spec.executable = '/bin/stress'
----> 5 spec.resource_spec = ResourceSpec(node_count=2, processes_per_node=2,
      6         process_count=2)
      7 # the line above should raise an 'psij.InvalidJobException' exception

TypeError: ResourceSpec() takes no arguments
```

Even when I pass in just `node_count=1` and no other kwargs to `ResourceSpec`, I get the same error:

```python
from psij import ResourceSpec
ResourceSpec(node_count=1)
```

I tried this using both the latest PyPI release and the `main` branch.

# Proposed Solution

I think the docs instead need to state that the user should be using `ResourceSpecV1` rather than the base `ResourceSpec` class?

**Comment by hategan** [comment]
Thanks for finding this. I now see that there are many instances of `ResourceSpec` being used incorrectly in the documentation.

`ResourceSpec` is an abstract class and cannot be instantiated. Instead, the documentation should use `ResourceSpecV1` as you point out.

That is also the reason you are seeing the `TypeError` instead of `InvalidJobException`. The latter should be raised when the numbers don't make sense (eg, node_count * processes_per_node != process_count), but what is raised is `TypeError` because you cannot instantiate `ResourceSpec`.

I found `ResourceSpec` being instantiated in examples in the spec and submitted an issue (https://github.com/ExaWorks/job-api-spec/issues/165).
A quick grep didn't show similar usage in psij-python docstrings. If there are any other places where you saw this, please let us know.

**Comment by arosen93** [comment]
@hategan: Thanks for the reply! Yup, that's what I figured out as well 😄 Just wanted to report it here. Didn't have a moment to submit a PR to patch the docs but hopefully shouldn't be too hard to do the find-and-replace!

**Comment by arosen93** [comment]
Feel free to close this issue if it's to be addressed in https://github.com/ExaWorks/job-api-spec/issues/165

**Comment by hategan** [comment]
@arosen93 No worries. Finding it is significantly more valuable (and harder, due to self-myopic effects) than fixing it once found.

**Comment by arosen93** [comment]
Closing this as duplicate since it's being addressed in https://github.com/ExaWorks/job-api-spec/issues/165. I didn't find instances of it in the Python API specifically. 👍
